#!/bin/bash

cut -c1 | paste -s | tr -d "[:blank:]"[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Ccut -c1 | paste -s | tr -d "[:blank:]"
