#!/bin/bash
echo "Best school" > "\*\\\'\"Best school[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[[Sc[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[S[C[C[C[C[C\"\'\\\*$\?\*\*\*\*\*:)"
